name: "Deploy Currency Converter"

on:
  workflow_dispatch: {}
  push:
    tags:
      - "currency-converter/v*"

env:
  PROJECT_PATH: CurrencyConverter.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      
      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r win-x64 --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      
      # - uses: actions/checkout@v2
      # - uses: vimtor/action-zip@v1
        # with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # pattern: bin/Release/net6.0-windows/win-x64/publish/*.exe
          # release-url: ${{ steps.create_release.outputs.upload_url }}
          # files: bin\Release\net6.0-windows\win-x64\publish\
          # dest: converter.zip
      # - uses: actions/checkout@master
      # - uses: actions/create-release@v1

      # - uses: csexton/release-asset-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pattern: ClassCommands/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
      #     release-url: ${{ steps.create_release.outputs.upload_url }}

      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'converter.zip'
          path: bin/Release/net6.0-windows/win-x64/publish/
